### ISSUE TITLE
 TestIngressWithPodRestartAndNetPol on dual stack is flaky 

### ISSUE THREAD

**Issue by fmoral2** [rancher/distros-test-framework#127] opened 2024-07-15 15:35 UTC
- testing `TestIngressWithPodRestartAndNetPol` on dual stack , sometimes its failing on the last check after redeploying the issue workload, but sometimes passes 

- see jenkins job for dual stack to reference

 

```
kubectl exec -n test-k3s-issue-10053 pod/client -- wget -O - http://10.42.1.11/
Connecting to 10.42.1.11 (10.42.1.11:80)
wget: can't connect to remote host (10.42.1.11): Connection refused
command terminated with exit code 1
```

**Comment by rancher-max** [comment] 2024-07-15 19:27
See pinned test in k3s_dual_stack for failing test directly.

**Comment by rancher-max** [comment] 2024-07-15 21:10
It appears this is actually working and was failing by design when using an older version! Closing this out as such

**Closed by rancher-max** 2024-07-15 21:10 UTC
